# Generated by Django 3.0.5 on 2020-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('channels', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(blank=True, to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='user',
            name='emotions',
            field=models.ManyToManyField(blank=True, to='posts.Emotion'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.Tag'),
        ),
    ]
