# Generated by Django 3.0.5 on 2020-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200424_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='count',
            field=models.IntegerField(blank=True),
        ),
    ]
