# Generated by Django 3.0.5 on 2020-04-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank='../media/user/default_profile.png', upload_to='user'),
        ),
    ]
