# Generated by Django 3.0.5 on 2020-04-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200423_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertag',
            old_name='user',
            new_name='content_object',
        ),
    ]
