# Generated by Django 3.0.5 on 2020-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200420_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='../media/user/default_profile.png', upload_to='user'),
        ),
    ]
