# Generated by Django 3.0.5 on 2020-04-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel'),
        ),
    ]
