# Generated by Django 3.0.5 on 2020-04-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channel',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.CharField(max_length=100),
        ),
    ]
