# Generated by Django 3.0.5 on 2020-04-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200423_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channel',
        ),
    ]
